services:
  php:
    build: 
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        APP_ENV: ${APP_ENV:-production}
        INSTALL_DEV_DEPS: ${INSTALL_DEV_DEPS:-false}
    container_name: slim-php
    volumes:
      - ./app:/var/www/html
      # Composerキャッシュを永続化（オプション）
      - composer_cache:/var/www/.composer
    networks:
      - slim-network
    environment:
      - PHP_FPM_USER=www-data
      - PHP_FPM_GROUP=www-data
      - COMPOSER_CACHE_DIR=/var/www/.composer
      - APP_ENV=${APP_ENV:-production}
      - INSTALL_DEV_DEPS=${INSTALL_DEV_DEPS:-false}

  web:
    image: nginx:latest
    container_name: slim-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - slim-network
    depends_on:
      - php

networks:
  slim-network:
    driver: bridge

volumes:
  composer_cache:
    driver: local
