services:
  mysql:
    image: mysql:8.4
    container_name: slim-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - slim-network

  php:
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local

networks:
  slim-network:
